name: 3DInfomax
channels:
  - dglteam
  - pyg
  - pytorch
  - conda-forge

dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - rdkit
  - pyg
  - dgl-cuda10.2
  - pot
  - numpy
  - certifi
  - click
  - tensorboard
  - ogb
  - icecream
  - fsspec
  - s3fs

  - pip:
    - pyaml
